### ISSUE TITLE
Label namen nach convention

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/AntWars#108]
Die Label namen in den GamePanel Statistiken sind nicht nach der convention
das `labelplayer1pointsshow` sollte zu `lbl_player1Points` sowie am  besten auch alle anderen Label's.
wenn `lbl_player1Points` schon der Text ist und nicht der Wert sollte der Wert inetwa soetwas sein:
`lbl_player1PointsValue`

**Comment by BroderPeters** [comment]
Konventionen sind für mich von allen festgelegte Bedingungen, an die es sich zu halten gilt.
Deine "Konventionen" wurden weder irgendwo nieder geschrieben, noch bewusst gelehrt.

**Comment by jmattheis** [comment]
naja wir haben das ja beim configurations panel gemacht, zum hauptteil ist es auch nicht wichtig das wir die ganzen konventionen alle einheiten, blos wir sollten es wenigsten einheitlich machen.

**Comment by BroderPeters** [comment]
Dem stimme ich zu.

**Comment by BroderPeters** [comment]
Was ist mit den Bezeichnungen im ConfigurationPanel?

**Comment by jmattheis** [comment]
sollten gleich mitgeändert werden wenn dort welche fehlen/nicht einheitlich sind.

**Comment by BroderPeters** [comment]
`numeric` kürzen?

**Comment by jmattheis** [comment]
ja nimm irgentwas wie `nmc` muss ja einheitlich sein das auch alles gekürzt ist (:
