### ISSUE TITLE
Konventionsübersicht

### ISSUE THREAD

**Issue by BroderPeters** [jmattheis/AntWars#109]
Bitte listet hier alle bekannten Konventionen auf.
Die Liste können wir anschließend in der Wiki verewigen.

**Comment by jmattheis** [comment]
Windows forms variablen namen: prefix von https://msdn.microsoft.com/en-us/library/aa263493(v=vs.60).aspx
`prefix_nameIrgentwas` (normal ist das ohne den _ aber wir habens überall sogemacht)

Const/static readonly variablen in capslock mit _ als trennzeichen von Wörtern `COOLDOWN_SOMETHING` (normal in c# macht man das anscheinend auch in nur PascalCase) 

MethodenNamen, Parameter, locale variablen in camelCase
Properties, KlassenNamen in PascalCase

**Comment by nicories** [comment]
Ich finde wir sollten uns lieber auf einen schon etablierten Styleguide für c# einigen, der z.B. auch die Reihenfolge der Konstanten/Properties/Methoden festlegt.

**Comment by BroderPeters** [comment]
Wenn es unseren bisher umgesetzten Konventionen widerspricht, bin ich dagegen, da dies eine grobe Änderung im kompletten Programm darstellt.

**Comment by jmattheis** [comment]
In direkt habe ich daran gedacht, Static readonly und const ganz oben, dann je nach Sichtbarkeit Variablen, danach Methoden welche auch nach Sichtbarkeit sortiert sind

**Comment by nicories** [comment]
Ich fände es auch ganz gut, wenn wir die Formatierung des Quelltexts einheitlich halten.
Ich bin da für die Standardeinstellungen, die Visual Studio mitbringt.
Automatisches Formatieren der derzeitigen Datei kann man mit ctrl+K & ctrl+D auslösen.

**Comment by jmattheis** [comment]
@nicolasries finde das wir da was eigenes benutzen sollten, ich mache mal etwas.

**Comment by BroderPeters** [comment]
@jmattheis Wie sieht es mit deiner Planung aus?

> @nicolasries finde das wir da was eigenes benutzen sollten, ich mache mal etwas.

**Comment by jmattheis** [comment]
Der pullrequest?

**Comment by BroderPeters** [comment]
Fail...

**Comment by nicories** [comment]
@jmattheis Die .vssettings Datei funktioniert beir mir irgendwie nicht. Ich kriege immer die Fehlermeldung, dass die Datei keine korrekt vssettings Datei ist.

**Comment by nicories** [comment]
Hat sich erledigt. Hatte noch VS2013, mit 15 geht das ohne Probleme.

**Comment by BroderPeters** [comment]
als ob ich bei meiner leitung updaten kann^^

**Comment by jmattheis** [comment]
Ich schließe dieses Issue mal, wenn es nochetwas zum hinzufügen/diskutieren gibt einfach wieder öffnen.
