### ISSUE TITLE
Analyse und Konzeption der Issues

### ISSUE THREAD

**Issue by BroderPeters** [jmattheis/AntWars#113]
Ich würde gern einführen, dass wir die Issues ausführlicher nutzen und wie eine Art Projektdokumentation führen.
Das heißt in einem Issue beschreibt der Assigne seine Analyse und Konzeption. (Zeitschätzung können wir weglassen)
So können die übrigen Entwickler überprüfen ob eine Aufgabe richtig verstanden wurde und ihr Feedback geben.
Der Vorgang erspart und unnötige Commits und Pull Requests und nähert das Projekt der richtigen Projektarbeit an.

Wie seht ihr das Thema?

**Comment by jmattheis** [comment]
+1
Ich würde auch hinzufügen dass wenn man bei größeren Issues wie `Random Events` oder `Upgrade Base` unter-Issues erstellt, so wie ich es beispielsweise bei Upgrade Base gemacht hab, dadurch können wir die Arbeit besser teilen und sehen Fortschritt besser und die Pullrequests sind nicht so groß.

**Comment by nicories** [comment]
Kann ich mich anschließen. Manche Issues sind etwas dürftig formuliert; oft reicht das, manchmal führt das aber dann schon zu Missverständnissen.

Unter-Issues sind auf jeden Fall auch eine gute Idee.

**Comment by BroderPeters** [comment]
Wie verhandeln wir mit Issues, die zwar geklärt sind, aber wie dieser hier zu Konventionen beitragen?

**Comment by nicories** [comment]
Könnte man vielleicht im Wiki zusammentragen. Unter dem Punkt Workflow oder so.

**Comment by jmattheis** [comment]
Ich schließe dieses Issue mal, wenn es nochetwas zum hinzufügen/diskutieren gibt einfach wieder öffnen.

---

Evtl sollten wir wirklich mal alles in einem Wiki Eintrag zusammenfassen
