### ISSUE TITLE
ControllableBoardObject

### ISSUE THREAD

**Issue by BroderPeters** [jmattheis/AntWars#118]
`ControllableBoardObjectt` wird aus `BoardObject` erstellt und erhält die Move-Methoden der `Ants`.

**Comment by nicories** [comment]
Ich glaube `MoveableBoardObject` ist nicht die richtige Bezeichnung, da hier noch andere Properties und Methoden reinkommen, die gar nichts mit dem Bewegen zu tun haben, z.B. Health, ViewRange.
Habt ihr noch eine bessere Idee? `IntelligentBoardObject` oder so was.

**Comment by jmattheis** [comment]
Ich bin für `ControllableBoardObject`.

**Comment by nicories** [comment]
Jo das klingt gut.

**Comment by jmattheis** [comment]
Mir ist hierzu noch eine andere Möglichkeit eingefallen, wird könnten die Methode in die `AIAntBase` hinzufügen, dadurch enthalten die Ameisen nicht direkt die Methoden, (Die Ameisen können die methoden immernoch haben aber internal) sodass in der AIAntBase diese nurnoch aufgerufen werden müssen oder mann kopiert die halt dahin)
Wenn das gemacht wird, brauchen wir keine verschiedenen Ameisen klassen, es würde dort einfach eine Enum mit dem AntType genügen.

**Comment by nicories** [comment]
Move-Methoden der Ameisen internal machen und die Schnittstelle in der AIAntBase aufrufen ist keine schlechte Idee.
Die verschiedenen Ameisen nur durch einen Enum abzubilden finde ich aber nicht so schön, weil man dann für spezifische Methoden wie kämpfen oder Signal abgeben immer den AntType abfragen muss. Das geht ein bisschen gegen die OOP Prinzipien finde ich.

**Comment by jmattheis** [comment]
> Die verschiedenen Ameisen nur durch einen Enum abzubilden finde ich aber nicht so schön, weil man dann für spezifische Methoden wie kämpfen oder Signal abgeben immer den AntType abfragen muss. 

In der AI müsstest du dann dort die Ameise zb nach `Scout` casten, was ungefähr aufs gleiche hinkommt, der Vorteil vom Enum ist, das man Ameisen Type einfacher hinzufügen kann.

**Comment by nicories** [comment]
Ja aber wir hätten dann eine Ant-Klasse mit allen Methoden; move, notifyOtherAnts. Die notify Methode darf aber nur der Scout benutzen, also muss man dort den Typ auch nochmal abfragen.
Ist nicht so schön, wie wenn das Objekt die Methode gar nicht erst hätte.

Oder ich verstehe das mit dem Enum gerade völlig falsch.

**Comment by BroderPeters** [comment]
Schwierige Frage. Ich stimme beiden Argumentationen zu. Einerseit wäre es gegen die OOP, die wir an den Tag legen. Andererseits aber eine elegante Lösung, die uns an einigen Stellen Code erspart.

**Comment by jmattheis** [comment]
In welcher Hinsicht verstößt das den gegen OOP?

**Comment by jmattheis** [comment]
BSP:
mit enum

```
if(ant.Type == AntType.Scout) { // kann auch isScout sein, muss dann nur das in der Methode prüfen
     ant.notifyOtherAnts(x);
}
```

momentan

```
if(ant.isScout()) {
    Scout scout = ant as Scout; // zum scout casten
    scout.notifyOtherAnts(null);
}
```

Das Problem mit der Enum wäre das man dann `ant.notifyOtherAnts()` auch auf ein Carries aufrufen kann, das müsste man natürlich in der methode überprüfen. und dann ggf eine Exception werfen.

**Comment by nicories** [comment]
Verstößt ist zuviel gesagt. Es ist einfach etwas realitätsnäher, wenn man unterschiedliche Ameisen in unterschiedliche Klassen aufteilt. Natürlich kann man den Typ auch über ein Feld abfragen.

Dass ein Objekt eine aufrufbare Methode hat, die immer eine Exception wirft, finde ich nicht so gutes Design.

**Comment by nicories** [comment]
Das Problem mit dem Casten könnte man auch lösen, indem man die `Scout#notifyOtherAnts` in die `Ant` Klasse verschiebt, dort eine Exception wirft oder false zurückgibt, und im `Scout` die Methode mit der richtigen Implementierung überschreibt. Dasselbe könnte man auch mit Warrior#fight machen
So hätten wir auch nochmal etwas mehr Polymorphie im Projekt.

**Comment by jmattheis** [comment]
@nicolasries in der `ControllableBoardObject`-Klasse müssen noch die Dokumentation Kommentare angepasst werden
