### ISSUE TITLE
Negative Ameisen Anzahl

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/AntWars#121]
![unbenannt](https://cloud.githubusercontent.com/assets/14895212/13892790/0b13cd26-ed5a-11e5-9378-b998fcc436bc.PNG)

**Comment by BroderPeters** [comment]
![2016-04-02 13_46_18](https://cloud.githubusercontent.com/assets/5406341/14226132/60a05c34-f8d9-11e5-839b-2d1e23d5d130.png)
