### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by nicories** [jmattheis/AntWars#124]
Wollen wir noch Tests für das Projekt einführen?
Wäre glaube ich auch ganz interessant für die Projektpräsentation und keine schlechte Erfahrung für uns, wie das mit C# so funktioniert.
Wobei ich zugeben muss, dass ich mich nicht ganz so gut auskenne, was Unit Testing betrifft.
Kleines Tutorial: https://msdn.microsoft.com/en-us/library/ms182532.aspx

**Comment by BroderPeters** [comment]
Kann erst frühestens am Donnerstag abend aktiv weiter arbeiten.
Aber wäre interessant das kennen zu lernen.

**Comment by jmattheis** [comment]
Ich hatte am Anfang mal gefragt ob wir unseren Code testen wollen, dort haben wir abgestimmt, und nein ist herrausgekommen, jetzt noch damit anzufangen halte ich für Zeitverschwändung, da kann man lieber noch 1-2 Issues fertig machen.

**Comment by nicories** [comment]
Ja ok, hast recht.  Vielleicht können wir das für das andere Projekt dann in Angriff nehmen.
Ich schließe das mal.
