### ISSUE TITLE
Methode nicht gefunden.

### ISSUE THREAD

**Issue by BroderPeters** [jmattheis/AntWars#129]
`+      $exception  {"Methode nicht gefunden: \"Boolean AntWars.Board.ControllableBoardObject.notifyOtherAnts(System.Collections.Generic.HashSet1<AntWars.Board.Coordinates>)\"."}  System.Exception {System.MissingMethodException}
`

Falsche RandomAI?

**Comment by jmattheis** [comment]
Bau dir doch selbst die KI ^^ und teste es

**Comment by BroderPeters** [comment]
Geht mir eher darum das jemand bei nem merge in den master ne fehlerhafte KI geschrieben hat..

**Comment by jmattheis** [comment]
Funktioniert doch alles?
Nur die DLL ist veraltet sowie alles dll's die da sind.

**Comment by BroderPeters** [comment]
Hast Recht. Ich bin davon ausgegangen, dass @nicolasries bei seinen letzten Änderungen auch die AI geupdatet hat.
