### ISSUE TITLE
Projektabschluss

### ISSUE THREAD

**Issue by nicories** [jmattheis/AntWars#131]
Wie in der E-Mail vorgeschlagen geht es hier darum, das Projekt auf einen Stand zu bringen, den wir präsentieren können, um es danach abzuschließen.
Im Moment sind noch einige Issues offen, manche mit recht viel Arbeit verbunden und meinetwegen nicht mehr unbedingt nötig. Ich liste einfach mal die auf, die wir von mir aus nicht mehr umsetzen müssen/sollten.
- Random Events #99 
- Grafiken #97 
- Coordinaten-Array #119

**Comment by BroderPeters** [comment]
Würde dem zustimmen.

**Comment by jmattheis** [comment]
+1 damits ist es entscheiden. Ich dachte das wir nach der Präsentation danach noch weiter arbeiten dürfen wieso dann Projektabschluss? Wenn das nicht so ist, bitte die Issues schließen.

**Comment by BroderPeters** [comment]
Wer sollte uns daran hindern weiterzuarbeiten?
Ich finde nur das wir nicht mehrere Projekt gleichzeitig laufen haben sollten. Können auch AntWars weiter führen.

**Comment by nicories** [comment]
Ich bin nicht absolut dagegen noch weiter an AntWars zu arbeiten, ich würde aber ehrlich gesagt lieber den Editor und das geplante Adventure Spiel angehen.
Da ist glaube ich auch ausreichend zu tun und, wie Broder schon sagte, sollten wir nicht allzuviel gleichzeit am Laufen haben.

**Comment by BroderPeters** [comment]
Also sollten wir dennoch eine Entscheidung treffen.
Auf jeden Fall machen wir AntWars präsentabel und stellen es vor.
Ob wir später durch zum Beispiel neue Kenntnisse durch die anderen Projekte daran weiter machen, steht uns ja offen.

**Comment by BroderPeters** [comment]
Also sollten wir dennoch eine Entscheidung treffen.
Auf jeden Fall machen wir AntWars präsentabel und stellen es vor.
Ob wir später durch zum Beispiel neue Kenntnisse durch die anderen Projekte daran weiter machen, steht uns ja offen.

**Comment by jmattheis** [comment]
Ich bin dafür, AntWars jetzt soweit präsentabel  zu machen, dann mit den anderen Projekten weitermachen, da ich diese als spannender sehe. Und wenn man mal Lust und Zeit hat, kann man ja auch noch AntWars zuende machen/ vielleicht bekommen wir ja in der Schule noch Zeit.

**Comment by BroderPeters** [comment]
@jmattheis Ich sehe den Issues, allein wegen seines Titels, noch nicht als abgeschlossen.

**Comment by jmattheis** [comment]
@BroderPeters hier wird aber auch nichts mehr gemacht. wir haben hier entschieden das wir die issues oben nicht machen, da muss das issue ja nicht offen sein.

**Comment by BroderPeters** [comment]
> Wie in der E-Mail vorgeschlagen geht es hier darum, das Projekt auf einen Stand zu bringen, den wir präsentieren können, um es danach abzuschließen.

Bei dem Issue geht es darum das Projekt auf einen präsentablen Stand zu kriegen. Ich hatte erst überlegt, dass hier vielleicht doch noch etwas geschrieben wird, aber ich denke das erledigen wir am Sonntag.
