### ISSUE TITLE
Random Numbers

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/AntWars#134]
Wie ihr ja bestimmt bereits bemerkt habt, wenn man mehrere Ameisen gleichzeit kauft, kommt es dazu das sich diese gleich bewegen.
Der Grund dafür ist, das C# Random klasse nicht True Random ist sondern nur ein PseudoRandomGenerator ist. Dieser generiert den seed anhand der system zeit --> gleiche nummern wenn das RandomObject zu der gleichen Zeit erstellt wird.

Lösungsansätze:
- `RNGCryptoServiceProvider` --> [Link](http://stackoverflow.com/questions/1234094/how-can-i-generate-truly-not-pseudo-random-numbers-with-c)
- Eigenen seed generieren vielleicht mit --> `Guid.NewGuid().GetHashCode()` [Link](http://stackoverflow.com/questions/1785744/how-do-i-seed-a-random-class-to-avoid-getting-duplicate-random-values)

**Comment by BroderPeters** [comment]
Ah, verstanden. Gute Erklärung

**Comment by BroderPeters** [comment]
> switch (rand.Next(0, 7))

Wieso ist keinem aufgefallen, dass das Switch-Case so gar nicht funktionieren kann?^^

> ```
>             case 7:
>                 Ant.moveUpperRight();
>                 break;
> ```

**Comment by BroderPeters** [comment]
> Eigenen seed generieren vielleicht mit --> `Guid.NewGuid().GetHashCode()` Link

Proved:

"Normal"
![2016-04-09 23_37_56](https://cloud.githubusercontent.com/assets/5406341/14406577/4fcd7986-feac-11e5-89f0-08ce2259535b.png)

Mit Guid.NewGuid().GetHashCode()
![2016-04-09 23_38_19](https://cloud.githubusercontent.com/assets/5406341/14406578/4fe85d0a-feac-11e5-9bad-dc7cfcb08001.png)

**Comment by jmattheis** [comment]
Der test muss übrings nicht zwangsläufig funktionieren da zwischen dem einen Erstellen vom Random Object und dem Anderen erstellen Zeit vergehen kann, und sich das auch verändern kann.

**Comment by BroderPeters** [comment]
Habe es auch InGame getestet.

**Comment by nicories** [comment]
Gefixt mit 547de4a.
