### ISSUE TITLE
Ameisenbesitzer in der AI nicht unterscheidbar

### ISSUE THREAD

**Issue by nicories** [jmattheis/AntWars#142]
Im Moment gibt es keine gute Möglichkeit in der AI zwischen eigenen und Ameisen des Gegenspielers zu unterscheiden.

**Comment by jmattheis** [comment]
Hast du eine Idee wie man das in der AI überprüfen sollte? Mir würde jetzt blos ein `Player` Object einfallen an dem die Properties internal sind.

**Comment by nicories** [comment]
Ich habe die Methode einfach der AIAntBase hinzugefügt. Nicht ganz so schön, weil die Methode eigentlich in der Ant sein sollte.
Commit: 1f9b19d

**Comment by jmattheis** [comment]
Das würde nur funktionieren wenn du es bei der gleichen Ameise machst, da jede Ameise eine eigene AI Instance hat.

**Comment by nicories** [comment]
Hoppla, stimmt..
