### ISSUE TITLE
UI Ameisen Farbe bei den Stats

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/AntWars#145]
Die Ameisen Farbe bei den Stats stimmt nicht überein, desweiteren sollten ggf. neue Farben gewählt werden die pro Player zusammenpassen aber sich von anderen Player deutlich unterscheiden.

**Comment by BroderPeters** [comment]
@jmattheis @nicolasries Was würdet ihr von der Möglichkeit halten, wenn der Spieler selbst die Farben bestimmen könnte? #UX

**Comment by jmattheis** [comment]
Eingentlich ist das gut, aber wenn man diese dann in der AI festlegen müsste könnten die spieler dort gleiche farben nehmen was ich für doof fände deswegen lieber feste farben.

**Comment by BroderPeters** [comment]
Könnte man abfangen, wäre aber Aufwand und ist nicht notwendig.
