### ISSUE TITLE
Speichern von der Configuration

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/AntWars#147]
Wenn man eine Configuration läd und sie später Speichern möchte wird man wieder gefragt, wo sie gespeichert werden soll.
Hier sollte das gleiche verhalten wie vorher sein, dass der Pfad zu der Datei die man zum Laden angegeben hat, auch zum speichern benutzt wird.

**Comment by BroderPeters** [comment]
Die Zwischenspeicherung des Pfades würde ich in die Gameconfig schreiben?
Oder gibt es besser Möglichkeiten?

**Comment by jmattheis** [comment]
Der ist bereits vorhanden, wird nur nicht auf loadConfig gesetzt.

**Comment by BroderPeters** [comment]
Habe das gerade kurz getestet.
Wenn ich nach dem Laden Speichere, ist doch der Pfad noch ausgewählt. Nur der Dateiname ist leer.

**Comment by jmattheis** [comment]
Es soll keinen Dialog öffnen, es soll es auf die bereits geladene Datei speichern.

**Comment by BroderPeters** [comment]
Aber wenn man die geladene Datei angepasst hat und als extra Datei speichern möchte?

**Comment by jmattheis** [comment]
Dann hat man pech gehabt?, normal wäre das ja die funktion "speichern unter" und nicht nur "speichern"? Es war btw schon immer so wie oben geschrieben.

> Wenn ich nach dem Laden Speichere, ist doch der Pfad noch ausgewählt. Nur der Dateiname ist leer.

Jain?, das ist das Standart zwischenspeichern vom letzten benutzten Pfad D.h. du lädst die config, und lädst dann eine AI die nicht im Config pfad ist, und nun ist der Pfad wenn man speichern drück auf der AI und nicht da wo die Config ist.

**Comment by BroderPeters** [comment]
> Jain?, das ist das Standart zwischenspeichern vom letzten benutzten Pfad D.h. du lädst die config, und lädst dann eine AI die nicht im Config pfad ist, und nun ist der Pfad wenn man speichern drück auf der AI und nicht da wo die Config ist.

Das war mir schon klar, dass es so funktionieren muss.
Werde es so umsetzen.

@nicolasries Was meinst du?
