### ISSUE TITLE
Zucker aufheben und verschwinden lassen

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/AntWars#15]
über eine Methode in `AIAnt` + zum Score hinzufügen (auch zum Money) und Zucken verschwinden lassen wenn `amount == 0`

**Comment by nicories** [comment]
@jmattheis Die Punkte kriegt man aber erst, wenn die Ameise in die Base zurückkommt, richtig?

Vielleicht wäre es da sinnvoll, den Weg zurück über eine Pathfinding-Methode zu ermitteln, die man in der AI benutzen kann.

**Comment by jmattheis** [comment]
@nicolasries Ja, die Punkte sollte man erst bekommen wenn die Ameise wieder in der Base ist.

Ja, so eine Methode die den Weg ausrechnet wäre gut.
