### ISSUE TITLE
Movement von der AIAnt limitieren

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/AntWars#16]
Momentan kann die `Ant` sich unendlich weit bewegen, das sollte dann limitiert sein.

**Comment by nicories** [comment]
@jmattheis Was soll passieren, wenn die Schritte aufgebraucht sind? Läuft sie zurück zur Base und lädt sich auf?

**Comment by jmattheis** [comment]
Okay, dass hab ich nicht gemeint, aber gut das du das ansprichst, in dem Issue soll es darum gehen das die ameise beim AI.antTick aufruf nicht unendlich weit laufen kann, das wird ja soweit ich weiß in der Config festgelegt, ich hatte mir dort soetwas gedacht, das wenn die Schritte aufgebraucht sind dass die methode zum move'n dann `false` zurück gibt.
Dann sollte es noch so eine methode wie `#canMove()` geben das man dann in der AI soetwas machen kann

```
while(ant.canMove()) {
    // move
}
```

Das was du ansprichst, sollte ja in der AI gemacht werden, dort sollten dann ggf. attribute an die Ant wo man sieht wieviel schritte die ant noch gehen kann bevor sie stirbt (was ja in der base reseted wird)

**Comment by drahenprofi** [comment]
Habe implementiert, dass wenn in der Ant-Klasse gespeichert wird wie viele Einheiten die Ameise schon gegangen ist. Im ConfigurationPanel kann die MoveRange zwischen 0 und 10 liegen. Welche Faktoren sollten da genommen werden? Kann sie sich bei 0 garnicht bewegen? Oder wird das von vornherein ausgeschlossen? 
Wie wird verfahren wenn die Ameise die max. Range erreicht hat? Momentan bleibt sie einfach stehen, ich finde es aber sinnvoller wenn sie zurücklaufen oder verschwinden würde. 
Wenn sie zurückläuft, welcher Weg wird eingschlagen? Da sie eh nicht schräg laufen kann würde ich vorschlagen, dass sie sich erst in X-Richtung und dann in Y-Richtung annährt. 
Wenn sie verschwindet was passiert dann mit dem getragenen Zucker? Logisch wäre ihn einfach liegen zu lassen.

**Comment by BroderPeters** [comment]
Gar nicht bewegen wäre ja quatsch, ich werde heute/morgen das configpanel entsprechend anpassen, dass es nur noch von 1 - 10 geht. 
Diesbezüglich müsste sowieso noch der Bewegungsfaktor bestimmt werden: Sprich, wenn 10, also Maximale Bewegungsreichweite, und wenn 1 minimale Bewegungsreichweite. Aber was ist viel und was wenig. und wir sollten die Boardgröße mit einbeziehen.
Die Frage mit verschwinden oder rückbewegung wurde vielleicht schon von den ki experten beantwortet: @jmattheis @nicolasries

**Comment by jmattheis** [comment]
Also die Ameise stirbt wenn sie sich nicht mehr bewegen kann. Momentan getragener Zucker resultiert in in einem Zuckerhaufen an der stelle wo die Ameise gestorben ist.

**Comment by drahenprofi** [comment]
Habe jetzt einen günstigen Faktor für die Skaliereung gewählt, die boardSize mit einbezogen und das ganze mit einer Ameise getestet. Kann man dann später ja immernoch ändern wenns nicht ganz passen sollte. 
Die Ameise verschwindet nun wenn sie out of range ist und hinterlässt ihren getragenen Zucker, das hab ich aber noch nicht getestet.

**Comment by jmattheis** [comment]
@arndtphillip Hab mir deine Änderungen einwenig angeschaut, du hast da etwas nicht berücksichtigt.
Es gibt sogesegen 2 Dinge einmal die Bewegungen nachdem die Ameise stirbt und einmal die Bewegungen die die Ameise in einem Tick machen darf. Kannst du dann noch ein Kommentar schreiben wieso in `BoardObjects#outOfRange(Ant)` hier das mit der spielfeld breite/höhe berechnet wird? `ant.UnitsGone >= ant.Owner.PlayerConfig.scoutMoveRange  * conf.boardHeigth * conf.boardWidth / 100`

**Comment by drahenprofi** [comment]
@jmattheis Das verstehe ich nicht, wie ich es sehe passieren in einem Tick, also der nextTick-Methode im Board 2 Dinge: zuerst werden in jeder Base neue Ameisen erzeugt (oder nicht) und dann wird jede Ameise in den BoardObjects bewegt. Dann muss ich nur dort gucken ob sie ihre maximale Range schon gelaufen ist und sie dann "sterben lassen". Oder was meinst du? 
Das mit der Breite und Höhe hatte Brodi ja schon angesprochen, einen kurzen Kommentar kann ich natürlich noch dahinter schreiben.

**Comment by jmattheis** [comment]
Momentan kann du dich in einem tick unendlich(soviel wie in der config steht) oft bewegen, so stand es schon oben im issue. Das soll limitiert sein, ich mache mal ein Beispiel: die Ameise darf insgesamt 50 felder laufen, aber nur 5 in einem tick, dafür fehlt ein attribute in der config.

**Comment by drahenprofi** [comment]
In jedem Tick bewegt sich jede Ameise doch nur einmal???

**Comment by jmattheis** [comment]
Nope, so war das jedenfalls nicht geplant, in der config gibt es moveRange und speed

**Comment by drahenprofi** [comment]
7cb6e8136ce5f589984de711ec07f04f33078751

Habs jetzt so limitiert, dass die Ameise so viele Schritte in einem Tick macht wie in der Carry- bzw. Scoutrange drin steht. Die Performance geht ein bisschehen runter wenn man 500 oder mehr Ameisen hat aber da sagte @jmattheis das das auch mit einem anderen issue zusammenhängen könnte

**Comment by jmattheis** [comment]
Du musst da mal noch den `master`-branch in deinen branch mergen, da gibt es konflikte, ich habe da auch schon 1 fehler endeckt, wenn du dann den pullrequest offen hast, schreibe ich die darein.
