### ISSUE TITLE
Neue Gewinnbedinung

### ISSUE THREAD

**Issue by BroderPeters** [jmattheis/AntWars#163]
Das Spiel soll auch beendet werden, wenn der Spieler keine Ameisen und kein Geld mehr besitzt.
In dem Fall gewinnt der jeweils andere Spieler.

**Comment by BroderPeters** [comment]
@jmattheis @nicolasries mir ist gerade folgende Situtation aufgefallen:
Spieler hat keine Ameisen mehr auf dem Feld, aber hat noch 1,9 Money.
Da der Warrior mit minimalen Attributen nur 1,88 kostet ist er kaufbar, die anderen Ameisen hingegen nur bei 2. Soll die Prüfung wirklich gleich null prüfen? ich glaube nämlich dass es zu einem genauen "null-wert" selten kommen wird, da sich die kosten ja dynamisch anhand der Attribute ergeben.

**Comment by jmattheis** [comment]
wenn < 1.88

**Comment by BroderPeters** [comment]
Ich lass es jetzt berechen, falls wir mal irgendwann etwas an den Faktoren schrauben. Macht es dynamischer.

**Comment by BroderPeters** [comment]
Da ich es unschön finden würde das bei jedem Tick zu berechnen, hatte ich überlegt den niedrigsten Kostenwert als `public const int` in dem `Helper#CostCalculator` zu schreiben.

**Comment by BroderPeters** [comment]
@jmattheis muss mich korrigieren. Kann `const` nicht nutzen, da ich den Wert erst bei Spielausführung setzen kann.

Edit: lasse es mit einer Methode `getLowestCostValue` zuweisen und kann dann doch const nutzen

**Comment by jmattheis** [comment]
nutze `static readonly`

**Comment by BroderPeters** [comment]
Edit of the Edit:
@jmattheis nehme `static`, konnst darf ick net.
Ist dat ok?

Edit: ok

**Comment by BroderPeters** [comment]
Beim Entwickeln ist mir aufgefallen, dass als geringster Wert nicht 1,88 berechnet wird, da @nicolasries vergessen hat im Kostenrechner (wo wir irrtümlich die 1,88 her haben) vergessen hat ein Feld im CostCalculator einzufügen (; . Habe ich nun gemacht:

![2016-04-19 21_32_59](https://cloud.githubusercontent.com/assets/5406341/14652850/8405e6da-0676-11e6-9161-d0e676229dc5.png)

**Comment by jmattheis** [comment]
kannst du die zahl gleich einwenig nach links schieben das die mit der nummer-box abschließt?
