### ISSUE TITLE
Erhöhen des Minimalwertes für Ticks pro Sekunde

### ISSUE THREAD

**Issue by BroderPeters** [jmattheis/AntWars#166]
Aus unbekannten Gründen ist der Mininalwert der Einstellung `Ticks pro Sekunde` auf "0", was eine Exception auslöst.

`System.DivideByZeroException`

Edit: Max auf 60 erhöhen

**Comment by jmattheis** [comment]
Wie kann man das reproduzieren?

**Comment by BroderPeters** [comment]
Na in dem man den Minimalwert in der Windows Form auf 0 setzt.
Edit: ich meine er kann auf null gesetzt werden. falsch ausgedrückt.

**Comment by jmattheis** [comment]
null ( nicht gesetzt) oder 0 jetzt ^^
nehme ja an 0 da man ja kein text in die numeric ding reinmachen kann.

**Comment by BroderPeters** [comment]
Ja ich meine die Zahl "0".

**Comment by jmattheis** [comment]
Welche Exception? sollt mann ggf auch hinschreiben :P
