### ISSUE TITLE
GamePanel score, money, time Anzeigen

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/AntWars#17]
Der Benutzer soll auf dem `GamePanel` auch ein paar Stats sehen.

**Comment by BroderPeters** [comment]
Benötigte Statistiken wären:
jeweils für beide Spieler: Punktestand, Geld, ?Anzahl der Ameisen?
für das Spiel: Stopuhr (Zeit steigend bis endwert, oder zeit sinkend von endwert?), Zucker im Spiel (Wie viel Zucker noch im Spiel ist, falls wir das abgreifen können)

Punkte mit Fragezeichen, bitte drauf eingehen.

**Comment by nicories** [comment]
Zeit sinkend ist besser. Anzahl der Ameisen kann man machen, außer es ist zu umständlich.

**Comment by jmattheis** [comment]
> Anzahl der Ameisen kann man machen, außer es ist zu umständlich.

Die bekommt man ja im `AIBase#nextTick` vielleicht kann man das da wiederverwenden, bzw das irgentwo anders speichern das dass nicht 2x berechnet wird.

**Comment by BroderPeters** [comment]
Möchte der User sehen von welcher Ameisenart er wie viele Ameisen hat?

**Comment by nicories** [comment]
Wär ganz gut glaube ich

**Comment by BroderPeters** [comment]
Na danke, jetzt darf ick dat gamepanel noch mal erweitern ^^

**Comment by BroderPeters** [comment]
![2016-01-07 20_14_20-gamepanel](https://cloud.githubusercontent.com/assets/5406341/12180190/6bfebaea-b57b-11e5-9952-46b2cbe495a5.png)
