### ISSUE TITLE
Zuckerkonfiguration in Prozent

### ISSUE THREAD

**Issue by BroderPeters** [jmattheis/AntWars#170]
Die Anzahl von Zucker auf dem Feld soll nicht mehr anhand fester Werte, sondern in Prozent bestimmt werden. Anhand des gewählten Prozentsatzes und der Pixelanzahl auf dem Spielfeld, wird die Zuckeranzahl berechnet.
Minimal sind 1% und maximal 95%.

**Comment by BroderPeters** [comment]
@jmattheis @nicolasries Zustimmung zu Min und Max werten der Prozente?

**Comment by jmattheis** [comment]
ist k

**Comment by nicories** [comment]
Ja!
