### ISSUE TITLE
Ant Kostenberechnung

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/AntWars#18]
Damit Carry und Scout mehr bzw weniger Kosten jenachdem welche Stats sie haben. Das sollte dann auch in den Player geschrieben werden, das die Ants richtig generiert werden können.

@BroderPeters hast du da schon was gemacht

**Comment by BroderPeters** [comment]
@jmattheis @nicolasries Ich habe mit der Entwicklung der Kalkulation begonnen, jedoch befinden sich in der Playerconfig keine Attribute für die kosten. Da der Player erst bei GameStart initaliziert wird und anhand der Playerconfig erstellt wird, würde ich entsprechende Attribute hinzufügen. Spricht etwas dagegen?

**Comment by jmattheis** [comment]
@BroderPeters Wenn du es so machst das die Attribute in der Playerconfig nicht mit in die xml geschrieben werden ja, dann musst du aber noch aus dem Player die Attribute entfernen da man das ja sonst 2x gespeichert hat.

**Comment by BroderPeters** [comment]
Aye Kapitän!

**Comment by BroderPeters** [comment]
An sich können die Attribute in die xml geschrieben werden. Sie werden sowieso nicht geladen, weil ich hier die felder explizit zuweisen muss. Beim Speichern kann ich es versuchen zu unterbinden

Edit.: Ist spontan zu aufwendig. Ich lasse es erstmal so. Funktioniert auch.

**Comment by jmattheis** [comment]
wenn man dann aber die Xml-Datei bearbeitet ist da ein Feld was effektiv nichts macht und so schwer ist das ja nicht das zu überspringen

```
[XmlIgnore]
public int ScoutCost { get; set; }
```

**Comment by BroderPeters** [comment]
wird gemacht
