### ISSUE TITLE
GameConfig settings implementieren

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/AntWars#19]
Zu implementieren ist:
1. StartMoney 
2. TimeInSeconds 
3. Points (Points sollte umbenannt werden oder eine überschrift wie 'winning conditions')

**Comment by BroderPeters** [comment]
@jmattheis Hier muss lediglich noch der "Spielstopper" eingebaut werden, da die Attribute bereits alle eingebaut sind. Stimmts oder habe ich recht?

Points ändere ich zu Winning Conditions

**Comment by jmattheis** [comment]
@BroderPeters Richtig.

**Comment by BroderPeters** [comment]
Bevor ich es möglicherweise wieder falsch einbaue, wo wäre der beste Punkt um die Abfrage zu starten? in jedem NextTick wäre eventuell, wenn auch nur leicht ressourcenlastig.

Und wie kann ick die Emails abstellen?

**Comment by jmattheis** [comment]
Ja im nextTick(), du musst es halt dann irgentwie hinbekommen im GamePanel den Timer zu stoppen.

In den einstellungen bei Notification Center :P

**Comment by BroderPeters** [comment]
Thanks God! war ja nicht mehr auszuhalten...

**Comment by BroderPeters** [comment]
Was möchtest du bei StarMoney noch implementieren?

**Comment by jmattheis** [comment]
Ist das fertig?

**Comment by BroderPeters** [comment]
noch nicht
