### ISSUE TITLE
Signal Implementierung 

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/AntWars#20]
Das irgentwie alle ameisen wissen ob irgentwo zucker ist wenn signal da ist. (Habe da schon ein paar ideen für, könnte man im TS besprechen oder ich mach das)

**Comment by jmattheis** [comment]
Ich habe mir das jetzt so gedacht:
1. 
- Das Signal bekommt ein Ziel (wo dann der Zucker ist)
- für jeden Zucker könnte es dann 2  Signale geben --> was viele sind, 
- die Frage ist dann wie es mit den Farben sein sollte

2.
- Zucker in einem Signal sind für alle Ameisen sichtbar die im Signal stehen, das Signal erweitert sich wenn andere Ameise dies setzt, Dadurch kann es dazu kommen das ein Spieler versucht auf der Kompletten map sein Signal zu haben.

Für beides
- Wenn die Ameise auf einem Signal steht kommt das Ziel/die Zuckerhaufen mit in `AI#antTick()` entweder mit in die `List<AIBoardObject>` oder als extra parameter.

2 wäre einfacher umzusetzten

Die AI bräuchte eigentlich noch eine größere Veränderung das die `antTick()` methode in eine Klasse kommt die für jede ameise eine eigene Instance hat, damit man da zb Ziele speichern kann.

@BroderPeters @nicolasries @arndtphillip Was haltet ihr davon, was findet ihr besser?

**Comment by nicories** [comment]
@jmattheis Sorry für die späte Antwort. 2 erscheint mir am besten.
Mit der AI hast du Recht, das müssen wir nochmal etwas überdenken. Da sollten wir vllt. mal per TS darüber reden.

**Comment by drahenprofi** [comment]
Was soll passieren wenn ein Zuckerobjekt in ViewRange von Scout oder Carry ist? Das Signal müsste sich dann logischerweise um die Ameise herum ausbreiten und nicht um den Zucker. Ist es besser das Signal erst auszusenden wenn die Ameise am Zucker ist?

**Comment by jmattheis** [comment]
> Was soll passieren wenn ein Zuckerobjekt in ViewRange von Scout oder Carry ist?

So gesehen nichts, das muss ja in der KI selbst programmiert werden

> Das Signal müsste sich dann logischerweise um die Ameise herum ausbreiten und nicht um den Zucker.

Richtig um die Ameise

> Ist es besser das Signal erst auszusenden wenn die Ameise am Zucker ist?

Das würde die KI nur unnötig limitieren, ich würde sagen solange es in der View ist.

**Comment by jmattheis** [comment]
Ich habe da nochmal einwenig nachgedacht, die 2. Lösung ist ziemlich schlecht, da man im Grunde nicht weiß zu welchem Zuckerhaufen das Signal gehört, deswegen würde ich sagen, das wir keine Signal objecte haben, sondern man als Scout ein "Signal" geben kann wo man in einer größeren Range als die viewrange, alle Ameisen benachrichtigt das da zucker ist. 
Die Ameisen AI hat dann eine methode `AIAnt#notfifySugar(Coordinates coords)`, dass man in der AI selbst entscheiden kann was man damit macht.
@nicolasries @BroderPeters @arndtphillip Was haltet ihr davon?

**Comment by jmattheis** [comment]
@nicolasries @BroderPeters @arndtphillip  ?!?

**Comment by BroderPeters** [comment]
Klingt gut. Sollten wir so umsetzen.

**Comment by jmattheis** [comment]
Wie ich es mir vorstelle:
`Scout` bekommt eine Methode `Scout#notifyOtherAnts(Coordinates[] coords);`
die `AIAnt` bekommt die Methode `AIAnt#notify(Coordinates[] coords);`.
Innerhalb der `Scout`-Methode, sollte wie bei der 'view' in der `AIAnt#antTick` ein Kreis berechnet werden und bei allen Ameise in diesem Kreis sollte die AI aufgerufen werden.
Somit sollte das eigentlich nicht soviel Arbeit sein.

Edit:
Die Methode `Scout#notifyOtherAnts(Coordinates[] coords);` muss ggf. in den `MovableAnt`-wrapper, welche dann nur ausgeführt werden darf wenn die Ant ein Scout ist.
