### ISSUE TITLE
GamePanel size

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/AntWars#25]
Die Größe der `GamePanel`-Form sollte sich nach den werten in der `GameConfig` richten,
Die bitmap wird ja um das 4x vergrößert, welches vielleicht einwenig viel ist. da sollte getestet werden wie es am besten aussieht.

**Comment by BroderPeters** [comment]
Habe mit der Aufgabe angefangen und die GamePanel-Size nach der Config ausgerichtet. Werde später noch wie beschrieben testen.

**Comment by jmattheis** [comment]
`config.Game.boardWidth * 4` eigentlich ist es ja doof wenn man 50x50 in der config nimmt und dann 200x200 bekommt oder?

**Comment by BroderPeters** [comment]
Stimme ich zu, ABER
1. Haben wir sowieso keine Einheit angegeben, also hat der Nutzer gar nichts zu "erwarten".
2. Richtet sich der Faktor 4 an  dem "Zoom" der gezeichneten Farbpixel. Würde ich nicht mit 4 multiplizieren, würde das Game nicht komplett zu sehen sein.

Entweder geben wir dem Nutzer einen Beispielwert vor der z.b. der Bildschirmauflösung entspricht, oder einen View-Button in dem ein leeres GamePanel geöffnet wird und er sich seine Auflösung anschauen kann.

**Comment by jmattheis** [comment]
1. dann brauchen wir ne Einheit dafür, naja das der Nutzer nichts zu erwarten hat ist eigentlich schlechtes UX

Wir können da ein Beispielwert und ein view button einbauen.

**Comment by BroderPeters** [comment]
Aber wie nennen wir die "Einheit"? durch den 4x zoom können wir nicht einfach sagen "pixel x4"

**Comment by jmattheis** [comment]
man kann auch einfach px nehmen und die größe dann / 4 nehmen ^^

**Comment by BroderPeters** [comment]
hm stimmt
mach ick

**Comment by jmattheis** [comment]
@BroderPeters ist das nicht schon fertig?

**Comment by BroderPeters** [comment]
Nein, ich muss noch die Bemerkung "in px*4" hinzufügen. Danach schließe ich den Issue.
