### ISSUE TITLE
Verbesserungsvorschläge für Projektarbeit

### ISSUE THREAD

**Issue by BroderPeters** [jmattheis/AntWars#29]
Für die Projektdokumentation würde ich gern ein Résumé schreiben, mit Punkten die zu verbessern wären, beziehungsweise bereits gut liefen. Hierfür bitte einfach Kommentare schreiben

**Comment by nicories** [comment]
Du meinst die Projektarbeit allgemein, oder? Also eine Art Schlussfolgerung, wie das Projekt bis jetzt gelaufen ist.

**Comment by BroderPeters** [comment]
Ja genau.

**Comment by nicories** [comment]
Gut finde ich:
- Die Arbeit und Kommunikation über Git/Github. Das ist mein erstes Projekt, an dem ich mit anderen Programmieren gleichzeitig arbeite, und ich finde das läuft recht angenehm so, wenn auch etwas gewöhnungsbedürftig zu Anfangs.
- Hoher Teameinsatz, dafür dass wir das in unserer Freizeit machen. Vorallem in den letzten paar Wochen sind wir ziemlich gut vorangekommen.

Verbesserungen:
- Wir hätten uns vorher etwas mehr Zeit für das Planen nehmen sollen. Hinterher merkt man halt, dass manche Sache einfach nicht ganz so gut durchdacht waren (Bsp. extra BoardObject-Klassen für die AI oder die BoardObjects, die Jannis jetzt mühselig in eine Klasse umbauen musste, damit das besser benutzbar ist).

Mehr fällt mir gerade nicht ein, ich überlege mir noch ein paar Sachen mehr..

**Comment by jmattheis** [comment]
Gut finde ich:
- Die Arbeit über GitHub, es war zwar am Anfang etwas kompliziert doch es hat sich denke ich mal gelohnt.
- Wir haben in der letzten Woche viel geschafft, das hätte ich mir am Anfang auch schon gewünscht (:

Zu Verbessern:
- Am Anfang haben wir Zeit in Planung gesteckt, dort haben wir aber leider nicht alles durchdacht/ bzw soweit gedacht. Wo durch das meiste davon wieder geändert wurde. --> dadurch hatte ich dann auch die meisten Konzepte gemacht, als ich an unserem Projekt arbeiten wollte, da wird wie etwas funktioniert nicht geplant hatten.
- Anfangs war die Beteiligung ziemlich mau, Ich hatte viele Fragen in den Mail's geschrieben, die eigentlich nie beantwortet wurden. Dort hätten wir uns dann mal zusammen setzten sollen, nicht das es so war wie jeder macht es so wie er denkt (jetzt bei größeren dingen auf die viel Aufbaut)
- Aufgaben Aufteilung (dies haben @BroderPeters und ich ja später festgelegt) das war nicht sehr durchdacht, da dort manches anderes gebraucht hatte --> das kann man dann wieder mit schlechter Planung begründen.
- Ist vielleicht ein wenig zu streng, Coding conventions benutzt, dass zb die Properties groß geschrieben werden. Es ist klar das wir die nicht alle kennen, doch momentan haben wir bei den Properties ein durcheinander, manchmal groß und manchmal klein.

---

Ich möchte dann auch nochmal einpaar Dinge von @nicolasries ansprechen

> Wir hätten uns vorher etwas mehr Zeit für das Planen nehmen sollen.

Da Stimme ich noch zu aber da weitere finde ich dann nicht mehr ganz richtig.

> Hinterher merkt man halt, dass manche Sache einfach nicht ganz so gut durchdacht waren (Bsp. extra BoardObject-Klassen für die AI 

Finde ich ehrlich gesagt nicht, ich habe ja viele der Konzepte gemacht, wie alles funktioniert.
Es gibt keine andere gute Lösung dafür, die einzige Lösung die mir damals noch eingefallen ist wäre alle Information wie Koordinaten, Anzahl des Zuckers usw separat vom Objekt zuhaben und das wäre schlechtes Design.

> oder die BoardObjects, die Jannis jetzt mühselig in eine Klasse umbauen musste, damit das besser benutzbar ist).

Ich denke nicht das das dadurch entstanden ist das es schlecht durchdacht ist, ich hatte mir darüber auch noch Gedanken gemacht, es gibt hier ein Paar mögliche Ansätze um die `BoardObject` zu speichern, ich möchte jetzt hier nicht so technisch werden deswegen sag ich mal einfach das jede ihre Vor- und Nachteile hat. + wir hatten das damals mit einer Abstimmung entschieden (:

**Comment by BroderPeters** [comment]
Wow, gleich soviel auf einmal. Gehe ich nachher mal in Ruhe durch und nehme das auf.
Was mir bereits jetzt positiv auffällt: @jmattheis du hast auf den ersten Blick ordentliche Sätze mit Rechtschreibung und Grammatik angewandt, dass klang in deinen E-Mails nie so (;

**Comment by nicories** [comment]
Ja, das kam vielleicht etwas zu negativ von mir rüber, so meinte ich das gar nicht. Insgesamt ist das schon ganz gut, und wir sind ja auch noch am Lernen. :)

**Comment by BroderPeters** [comment]
Wie fandet ihre den Kenntnisstand über die Fachkenntnisse der Teammitglieder?
Ich für meinen Teil kann rückblickend einiger Maßen die Programmierkenntnisse einschätzen, aber ich denke es wäre von Anfang an wichtig gewesen zu wissen wer was wo und wie kann, um die Aufgabenverteilung einfacher zu gestalten.
