### ISSUE TITLE
Projektdokumentation

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/AntWars#3]
@BroderPeters

**Comment by BroderPeters** [comment]
Haltet ihr @jmattheis @nicolasries @arndtphillip es für notwendig die Projektdokumentation auf den aktuellen Stand zu bringen?

**Comment by jmattheis** [comment]
kp wäre schon schön sowas zu haben, aber denke nicht das es so notwendig ist

**Comment by BroderPeters** [comment]
Problem ist dass ich die inhaltlich gar nicht mehr alleine zusammenkriegen, da du und nicolas mehr Ahnung von der Materie habt die wir verwenden. 

Ansonsten, schön sieht sie nicht wirklich aus, diente bisher eher als Absicherung vor El-Khamsi, falls wir was zeigen sollen.
