### ISSUE TITLE
Fehlerbehebung: Zweites Starten des Spiels

### ISSUE THREAD

**Issue by BroderPeters** [jmattheis/AntWars#34]
Beim zweiten Starten der Start-Aktion tritt die System.ObjectDisposedException im Aufruf der "Show()"-Methode auf.
Dieser müsste behoben werden, damit der "View"-Button einen Sinn ergibt.

**Comment by nicories** [comment]
Das Problem tritt auf, wenn man das Game-Panel schließt und dann über View oder Start nochmal öffnen will, weil Windows Forms beim Schließen alle Resourcen löscht.
Ein einfacher Fix wäre, das Schließen einfach zu verbieten.

**Comment by jmattheis** [comment]
Ja, oder das Game-Paneleinfach neu initialisieren, einfach ein neues Object davon erstellen.

**Comment by nicories** [comment]
Stimmt, ist noch besser. Ist gepusht. #37
