### ISSUE TITLE
Config-Änderungen während der Laufzeit

### ISSUE THREAD

**Issue by nicories** [jmattheis/AntWars#38]
Im Moment ist es möglich, die drei verschieden Configs zu ändern, während das Spiel läuft. Die Änderungen werden sofort übernommen, was bspw. beim Verkleinern der Kartenmaße sehr schnell zu Exceptions führt.

**Comment by jmattheis** [comment]
Ich würde sagen Config Panel nach start deaktivieren, und wenn das gamepanel geschlossen wurde, alles wieder aktivieren.
