### ISSUE TITLE
Inhalte des Schulhalbjahres

### ISSUE THREAD

**Issue by BroderPeters** [jmattheis/AntWars#41]
Herr El-Khamsi hat die Projektarbeit im Unterricht unter der Vorraussetzung genehmigt, dass wir die Inhalte des Schulhalbjahres mit einbringen. Um diesem Punkt Ausdruck zu verleihen, werden wir die Inhalte auflisten und in der Projektdokumentation mit Beispielen kurz erläutern.

Falls ein Themengebiet nicht aussagekräfitg genug erscheint, schaut zuerst auf Moodle unter dem Thema nach, bevor ihr es hier hinterfragt.
Bei Fragen und Änderungswünschen einfach kommentieren.

Hierzu bitte Beispiele für folgendene Themen nennen:
- Implementierung von Klassen
  - Properties
  - Konstruktoren
- Spezifizierung von Klassen
- Statische Methoden
- Überladen von Methoden
- Rückgabe- und Übergabeparameter
- Arrays
- Call by Value, Call by Reference
- Sichtbarkeit
- Datenkapselung
- Geheimnisprinzip
- Klasse
- Objekt
- Methode
- Zugriffsmodifizierer für Klassen und Members
- Namespaces
- Konstruktoren
- Kardinalität/Multiplizität
- Vererbung
- Polymorphie
- Abstrakte Klassen
- Schnittstellen

**Comment by nicories** [comment]
> Properties

Die Antwars.AI.AIBase Klasse bzw das IAI Interface benutzt Properties mit unterschiedlich sichtbaren Gettern/Settern.

> Konstruktoren

Die Klassen unter AntWars.AIs.Converter.Classes haben alle Konstruktoren, die den Konstruktor der Elternklasse wiederum aufrufen.

> Statische Methoden

Die Hilfsmethoden in der AntWars.Helper.Utils Klasse sind alle statisch, sodass die Klasse nicht instanziiert werden muss.

> Überladen von Methoden

Benutzen wir einmal in der AntWars.Board.Board Klasse für die nullTick-Methode. Ein zweites Beispiel wäre in der AntWars.Helper.Utils Klasse die generateBaseCoords-Methode.

> Rückgabe- und Übergabeparameter

AntWars.Board.BoardObjects.getBoardObjectsFromCoords nimmt ein Objekt vom Typ Coordinates als Parameter und gibt ein Objekt vom Typ IList mit BoardObject-Objekten zurück.

> Sichtbarkeit/Datenkapselung/Geheimnisprinzip/Zugriffsmodifizierer

Die AntWars.Board.Board Klasse hat public Methoden, die als Schnittstelle dienen, und einige als private deklarierte Methoden, die nur innerhalb der Klasse aufgerufen werden können.

> Namespaces

Benutzen wir in jeder Klasse zur logischen Aufteilung in mehrere Teile unseres Programms. Die Namespaces spiegeln auch die Verzeichnisstruktur wider.

> Kardinalität/Multiplizität

Kann man ganz gut an der BoardObjects Klasse sehen. Die Board Klasse hat die Property "BoardObjects" (Kardinalität 1), die BoardObjects Klasse hat als Attribute mehrere Listen, die Instanzen von den verschiedenen von BoardObject ableitenden Klassen beinhalten (Kardinalität *).

> Vererbung

Carry erbt von Ant, die von BoardObject erbt.

> Polymorphie

Wird in der Player1 und Player2 Klasse angewandt, dort haben selbe Methoden-Namen unterschiedliche Implementationen.

> Abstrakte Klassen

AntWars.AI.AIBase ist eine abstrakte Klasse mit mehreren abstraken Methoden, die in den Player1 und Player2 Klassen überschrieben werden müssen.

> Schnittstellen

AntWars.AI.AIBase implementiert das IAI Interface, das wiederum von der Klasse AntWars.Player als Property definiert ist.

**Comment by jmattheis** [comment]
@BroderPeters kann das geschlossen werden? wenn ja, dann tue dies bitte.
