### ISSUE TITLE
Selbstständiges Beenden des Spiels

### ISSUE THREAD

**Issue by BroderPeters** [jmattheis/AntWars#44]
Anhand der Einstellung "Time in secounds" im ConfigPanel sollte auch das Spiel nach Ablauf der Zeit stoppen.

**Comment by jmattheis** [comment]
Schau #19 das issue gibt es schon :P

**Comment by BroderPeters** [comment]
naja, wie mans nimmt ^^
klingt dort ziemlich ungenau ^^

**Comment by jmattheis** [comment]
Kannst es ja gerne ausführlich da hin schreiben, jedenfalls ist das doof wenn es 2 issues gibt die das selbe Inhalten (wenn auch nur ein teil)
