### ISSUE TITLE
Langsames GamePanel nach > 2min

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/AntWars#46]
Wenn man das Spiel einwenig laufen lässt, dann kommt es dazu das nurnoch 1 tick in der Sekunde passiert, dies ist natürlich nicht gewollt. In diesem Issue geht es darum die Ursache zu finden und zu beheben. Ich würde sagen das es das Convertieren von den BoardObject's zu den AiBoardObject's ist zu 100% sicher bin ich mir da aber auch nicht.

**Comment by nicories** [comment]
Ich bin gerade dabei das zu verbessern, daran liegt das aber so wie ich das sehe tatsächlich gar nicht. Wenn du du den Methodenaufruf in getBoardObjectsInView auskommentierst, läuft das immer noch sehr langsam nach einer gewissen Zeit.

**Comment by jmattheis** [comment]
@nicolasries bei mir läuft alles super wenn ich die getBoardObjectsInView methode auskommentiere

**Comment by nicories** [comment]
Das Problem besteht leider immer noch.
Wenn ich das Geld hochsetze fängt das Spiel nach einer Zeit an stark zu laggen mit der RandomAI.dll geladen.

**Comment by jmattheis** [comment]
So so so, ich habe jetzt mal mit einem Profiler der die performance testet, das Programm getestet, dort habe ich auch den überltäter gefunden, leider weiß ich nicht wir wir das fixen sollen, da es eigentlich schon ein sehr performanter weg ist den wir da haben:
Ich habe das Programm 1000 ticks laufen lassen dies hat 620 Sekunden also  ca 10 Minuten gedauert, es wurden dort insgesmmt 1000 Ameisen generiert, eigentlich sollten das nur 1min und 40 Sekunden sein.
Dabei bin ich zu dem Ergebnis gekommen, das das programm 74% der zeit also ca 480 sekunden in der `#TryGetValue` methode in der `BoardObjects#getBoardObjectsFromCoords()` methode befindet.
![profiler](https://cloud.githubusercontent.com/assets/14895212/13075323/8d8aeb86-d4aa-11e5-8670-0aff3ee691b5.JPG)

**Comment by jmattheis** [comment]
so so so, hab dann mal das Dictionary durch ein array ausgetauscht, es ist um 200% schneller geworden, es ist aber immernoch zu langsam. es schafft die 1000 ticks (1min 40 sec) in ~200 sekunden das heißt es muss noch verbessert werden.
Die `#getCoordsInView(Ant)` methode kann man bestimmt noch verschnellern, da die allgemein noch viel zeit frist.
![profiler](https://cloud.githubusercontent.com/assets/14895212/13077868/c5f7c1e0-d4bb-11e5-974f-f8fd0c89a89f.JPG)

**Comment by nicories** [comment]
Ich sehe auf jeden Fall ein Problem mit der Board#getBoardObjectsInView(Ant ant) Methode. Die ruft _getBoardObjectsFromCoords_ einfach extrem oft auf.

**Comment by jmattheis** [comment]
EDIT: es sind die ameisen anzahl \* ticks somit wenn man 1000 Ameisen hat und die 1000 Ticks laufen lässt kommen da 1.000.000 aufrufe raus.

Anwendungs Beispiel
wenn man jeden tick eine Ameise kauft, dann kommt man nach 1000 Ticks auf 2k Ameise somit ist der wert richtig.

**Comment by jmattheis** [comment]
so so so, mit multithreading sieht das jetzt schon anders aus: es läuft soweit fllüssig, ist aber immernoch zulangsam, was zu verändern ist:

`GamePanel#print`
- `Bitmap` initialisation muss die sein, kann man die `Bitmap` "cleanen"?
- muss immer `Bitmap#GetPixel` aufgerufen werden?, kann man das zwischenspeichern

`GamePanel#calcGameStatistics`
- nur verändern wenn sich der Wert wirklich verändert hat

`Board#getAllFromBoardInViewRange`-Ansatz überdenken ?!?

nach ~3000ticks
![profiler](https://cloud.githubusercontent.com/assets/14895212/13107276/27df90fc-d56d-11e5-9fa3-a228e177f459.JPG)

**Comment by jmattheis** [comment]
Problem gefunden, der `System.Windows.Forms.Timer` und auch eigentlich alle vorhanden Timer in c# sind nicht genau, so kommt es das man wemm man 100msx1000ticks welches 100.000ms sind, doch das programm läuft dann bereits 110.000 ms. Somit ist der timer ungenau, alternativ gibt es den Multimedia Timer (http://stackoverflow.com/questions/4212611/raise-event-in-high-resolution-interval-timer) den sollten wir dann benutzten.

**Comment by jmattheis** [comment]
Update.
![profiler](https://cloud.githubusercontent.com/assets/14895212/13696043/0b0e2ef8-e764-11e5-9a19-3f4b16b878b6.JPG)

**Comment by nicories** [comment]
Vielleicht sollten wir die Coordinates nicht immer neu erstellen, sondern stattdessen die X und Y Werte der Coordinates der Ameisen verändern?
Das Spiel läuft aber flüssig auch mit extrem vielen Ameisen, wird nur sehr CPU-lastig mit der Zeit.

**Comment by jmattheis** [comment]
> Vielleicht sollten wir die Coordinates nicht immer neu erstellen, sondern stattdessen die X und Y Werte der Coordinates der Ameisen verändern?

das hat nichts mit den 7.6 Sekunden auf dem Bild zutun schaue dir mal die getBoardObjectsInView methode an

**Comment by jmattheis** [comment]
Man könnte dort denke ich das auch ohne ein neues Coords object machen, in dem man einfach mit x und y weiter arbeitet, müsste man halt die methoden anpassen

**Comment by nicories** [comment]
#92 aufgemacht. Ist aber bisher noch nicht so der Hit.

**Comment by jmattheis** [comment]
Einstellungen viewrange = 10; 40 ticks per second; 600 ticks; 9999 money; 1 Ameisen kauf pro tick
![ty](https://cloud.githubusercontent.com/assets/14895212/14255519/aadb166a-fa94-11e5-96da-a6604973d6c9.png)
