### ISSUE TITLE
AIAnt move methoden in der view von der Ameise

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/AntWars#47]
Momentan ist es möglich, Ameisen in der view von der momentanen Ameise zu bewegen:
`nextTick(AIAnt ant, List<AIBoardObject> view)`. Dies sollte nicht machbar sein.

**Comment by nicories** [comment]
Hat sich erledigt mit den internal Settern der Coordinates.

**Comment by jmattheis** [comment]
Falsch. Ist jetzt halt in der Ant die methoden zum moven.

**Comment by nicories** [comment]
@jmattheis Move-Methoden sind mit der Wrapper Klasse in #80  vorerst geregelt, wir haben aber noch dasselbe Problem mit allen public Methoden der Ant-Klasse, oder? Es müssten also eigentlich alle der Methoden in die Wrapper Klasse.

**Comment by jmattheis** [comment]
@nicolasries jap die müssten eigentlich auch darein

**Comment by nicories** [comment]
Ich mach mal ein neues Issue hierfür auf.
