### ISSUE TITLE
Erstellen von einer Beispiel KI

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/AntWars#51]
Titel sagt alles (:
requires #16

**Comment by jmattheis** [comment]
Würde sagen jeder erstellt eine KI, das wir dann hoffentlich unterschiedliche Ergebnisse/Lösungen haben

**Comment by BroderPeters** [comment]
@nicolasries @arndtphillip  Bitte noch eine eigene KI erstellen und als dll in den AI ordner einpflegen.

**Comment by jmattheis** [comment]
Wenn man die view durch iteriert sollte man das mit einem for loop machen:

```
for (int i = 0; i < view.Length; i++)
{
    BoardObject obj = view[i];
    if (obj.isSugar())
    {
        // do something 
    }
}
```

**Comment by BroderPeters** [comment]
Dat AI-Skript...
![2016-04-19 19_46_12](https://cloud.githubusercontent.com/assets/5406341/14649496/9fc97814-0667-11e6-8bbd-07c51e51af4a.png)

Edit:
Fail, mir ist gar nicht aufgefallen, dass ich im AntTick gar keine MoveMethode aufrufe...
Aber falls es jemand interessiert, wie das Spawnverhalten an der Base aussieht... Bitte

**Comment by jmattheis** [comment]
Ist ja gewollt lul?

**Comment by BroderPeters** [comment]
Ja sorry bin dumm.

**Comment by jmattheis** [comment]
@nicolasries wie siehts aus schaffst du deine KI bis morgen?

**Comment by nicories** [comment]
jojo, bin da dran
