### ISSUE TITLE
moveUp und moveDown methoden der Ant sind vertauscht

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/AntWars#57]
steht im title (:

**Comment by nicories** [comment]
Die Methoden sind in Ordnung, das Problem ist die Y-Achse, die irgendwie oben mit 0 anfängt.

**Comment by jmattheis** [comment]
Jain, die Methoden sind falsch, da es kein richtiges Coordinaten System ist, es ist 

```
0 - 1
|
1
```

somit wenn man `y++` macht geht es nach unten.

**Comment by nicories** [comment]
Ja genau, das ist aber finde ich nicht so gut nutzbar bzw. verständlich. Auch für die AI, wenn man den View übergeben bekommt.
Ich ändere das aber erstmal in den Move Methoden.
