### ISSUE TITLE
Coordinaten vergleich mit referenz ist falsch

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/AntWars#59]
Mir ist aufgefallen das im code `Coordinates == Coordinates` benutz wird, dieses bezieht sich auf die Object referenz:

```
Coordinates coords1 = new Coordinates(1,2);
Coordiantes coords2 = new Coordiantes(1,2);

(coords1 == coords2) == false
```

das wird zb gerade bei der `Ant#dropSugarOnBase()` benutz, stattdessen sollte die `Coordiantes#Equals(object)` methode genutz werden.
Desweiteren sollte geprüft werden ob das irgentwo anders noch ohne `#Equals` genutz wird.

**Comment by jmattheis** [comment]
in der oben genannten Methode funktioniert es dennoch, d.h. irgentwo wird die referenz gesetzt, das sollte nicht passieren, da sich Coordinaten ja verändern.
Es gibt hier 2 Lösungs ansätze:
1. `Coordinates` unveränderbar machen dh, x und y kann nur im constructor gesetzt werden ( würde ich bevorzugen)
2. Überall die `#clone()` methode benutzen und nich die referenz übergeben.

**Comment by nicories** [comment]
Konstruktor halte ich auch für die bessere Variante, erledige ich.
