### ISSUE TITLE
Kampfsystem

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/AntWars#72]
Ameisen sollen kämpfen können, 
Ziel des Issues ist ein Konzept zu inwerfen und zu implementieren

**Comment by BroderPeters** [comment]
> inwerfen

*entwerfen
Find ick geil (also dat thema)

**Comment by nicories** [comment]
Neue Ameise: **Warrior**. Bekomt das zusätzliche Attribut "Attackpower" und eine Methode, mit der sie andere Ameisen angreifen kann. Sie kann aber keinen Zucker tragen.
Alle Ameisen bekommen noch das zusätzliche Attribut "Health".

Kampf läuft so ab, dass die Warrior-Ameise einen Kampf initiiert und den ersten Schlag bekommt. Dann kann die andere Ameise entscheiden, was sie machen will, fliehen oder kämpfen. 1 Schlag macht 1 \* Attackpower Schaden an Health.

**Comment by jmattheis** [comment]
> 1 Schlag macht 1 \* Attackpower Schaden an Health.

oder einfach 1 Schlag macht Attackpower Schaden (:

**Comment by BroderPeters** [comment]
Wieso haben alle anderen Ameisen keine Angriffstärke? So können nur Warrior gegen warrior

**Comment by jmattheis** [comment]
Warrior können nicht warrior angreifen

**Comment by BroderPeters** [comment]
Wieso nicht?
Sind Warrior nur dazu gedacht Nicht-Warrior zu killen?

**Comment by nicories** [comment]
Also meine Idee war:
Warrior können alle angreifen, auch andere Warrior. Scout/Carry können aber gar nicht kämpfen und müssen weglaufen.

**Comment by jmattheis** [comment]
Würde es so wie @nicolasries machen, würde sagen das man beim warrior auch inventar hinzufügen kann, welches dann aber teurer ist als bei einem nicht warrior.

**Comment by BroderPeters** [comment]
Stimme zu.

**Comment by BroderPeters** [comment]
@jmattheis @nicolasries Ist das Thema noch aktuell und wird umgesetzt? (Zur Umsetzung des Kostenrechners)

**Comment by jmattheis** [comment]
Ich denke ja.

**Comment by nicories** [comment]
Ich glaube wir sollten das erst einmal hinten anstellen und uns auf die anderen Sachen konzentrieren.

**Comment by nicories** [comment]
Sollen Carry und Scout auch kämpfen können? Natürlich mit erhöhten Kosten beim Kaufen.
Würde es in der AI einfacher benutzbar machen.

**Comment by BroderPeters** [comment]
Wäre dafür.

**Comment by BroderPeters** [comment]
@nicolasries Wie kommst du mir dem Kampfsystem voran?

**Comment by nicories** [comment]
Ich bin da dran. Hatte die Woche leider nicht so viel Zeit. Bis morgen pushe ich da nochmal etwas.

**Comment by BroderPeters** [comment]
Kannst du definieren bis wann der Issue fertig ist, da sich die Entwicklung der AI, welche Ausschlag gebend für die Projektpräsentation ist, an dem Modul orientiert?

**Comment by nicories** [comment]
Die Grundstruktur ist fertig in #152 . Im Moment gibt es noch ein paar Bugs, an der Funktion und Benutzung in der AI wird sich aber eher nichts mehr ändern.
Ich hoffe ich kriege das heute noch gelöst.

**Comment by jmattheis** [comment]
Noch die WarriorCount in die AIBase machen
