### ISSUE TITLE
Kostengenerator als extra Form hinzufügen

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/AntWars#74]

**Comment by jmattheis** [comment]
Hier drin sollte auch eine neue Kostengeneration erstellt werden, das z.B. der Scout billiger viewrange haben kann als ein carry usw.

**Comment by BroderPeters** [comment]
und carry günstigeres Inventory

**Comment by BroderPeters** [comment]
@jmattheis @nicolasries ich würde die Methode zur Kostenberechnung in der AIBase.cs erstellen, da hier auch Methoden wie buyCarrier und buyScout vorhanden sind.

**Comment by jmattheis** [comment]
Denke das währe nicht der richtige Ort weil du ja auf die Methode/n in einer anderen Form zugreifen musst, und das dann allgemein nichts mit der KI zu tun hat, würde es in einer neuen Klasse in `AntWars.Helper` machen.

**Comment by BroderPeters** [comment]
Hätte gedacht das die Methode dann von der AI aufgerufen wird und als Rückgabe die Kosten bekommt.

**Comment by jmattheis** [comment]
Jep, das ist richtig, aber im issue steht `extra Form hinzufügen` also soll eine grafische oberfläche dasein womit der User werte testen kann wv wann was kostet. Da dies nicht in der KI geschied gehört die berechnung dort auch nicht hin

**Comment by BroderPeters** [comment]
Dann werde ich die Berechnung als Methode der neuen Klasse (Form) hinzufügen.

**Comment by jmattheis** [comment]
Nicht zur Form (:, da die Berechnung ja auch in der KI benutzt wird und es da doof wäre die Form immer aufzurufen

**Comment by BroderPeters** [comment]
Ok, habe AntWars.Helper vorhin überlesen.

**Comment by BroderPeters** [comment]
@nicolasries @jmattheis Was soll aus der Kalkulationsmethode zurückgegeben werden, wenn einer der übergebenen Parameter (ViewRange, MoveRange, Inventory) größer als 10 oder kleiner als 1 ist, und somit nicht in dem von uns vorgegebenen Bereich liegt.

Ne Message:"Nicht schummeln"?

**Comment by jmattheis** [comment]
es soll eine `ArgumentException` geworfen werden. Die dann auch aufgefangen wird, das das spiel abbricht und eine nachricht wie "parameter x muss ziwschen x und y sein"

**Comment by nicories** [comment]
Exception ist gut, stimme zu.

**Comment by BroderPeters** [comment]
Thanks!

**Comment by BroderPeters** [comment]
![2016-03-12 16_32_00](https://cloud.githubusercontent.com/assets/5406341/13723790/fca20aa8-e86f-11e5-9c76-cbe0ade7dae3.png)

Zur Berechnung der Kosten für eine Ameise möchte ich dass die Funktion erkennt für welche Ameise berechnet wird. Ursprünglich wollte ich hierbei einfach eine temporäre Ameise übergeben, was sich jedoch als schwachsinnig herrausstellte. Nun meine Frage: Soll ich der Methode einfach n String à la "Carry" bzw. "Scout" übergeben oder ne Nummer? @jmattheis @nicolasries Bitte um Meinungen

**Comment by jmattheis** [comment]
ich würde nur eine Ameise übergeben diese enthält die viewrange moverange und das inventory (:
wieso ist das schwachsinnig?

**Comment by BroderPeters** [comment]
weil ameise erstellen "aufwendig" ist

**Comment by jmattheis** [comment]
Ne ist es nicht da es nicht sooft passiert, schau mal hier https://github.com/jmattheis/AntWars/blob/master/AntWars/AI/AIBase.cs#L89 da gibts schon ne ameise also muss man keine neue machen

**Comment by BroderPeters** [comment]
Sorry, aber das check ich nicht. Ich benötige doch eine Ameise bereits vor Spielbeginn, falls die Form aufgerufen wird.

**Comment by jmattheis** [comment]
ja das ist doch dann egal bei performance (:

**Comment by jmattheis** [comment]
erstellste dann einfach eine ^^

**Comment by jmattheis** [comment]
das kann geclosed werden?
