### ISSUE TITLE
Statusfarbe in LoadPlayerAI

### ISSUE THREAD

**Issue by BroderPeters** [jmattheis/AntWars#78]
>  BroderPeters added a note 3 minutes ago
> 
> Ist meiner Meinung nach nicht nötig, da durch die Änderungen von @nicolasries , dass die PlayerAIPaths in die Gameconfig kommen, ich keine Exceptions mehr bekommen kann, da durch Aufruf des "Neu"-Buttons die Gameconfig initializiert wird.
> @jmattheis
> Owner
> jmattheis added a note 2 minutes ago
> 
> Dann kannst du dies Mergen, aber im Issue bitte schreiben das das auffangen von der Exception zu entfernen ist.

**Comment by jmattheis** [comment]
Du kannst dort auch gleich checken ob es eine Valide dll ist indem du `new AILoader(path)` machst wenn das keine `InvalidDLLFileException` wirft, dann ist die dll valide.

**Comment by BroderPeters** [comment]
Mach ich. Setze mich am Wochenende oder spätestens nächste Woche ran.

**Comment by BroderPeters** [comment]
@nicolasries Ist der PlayerAIPath bereits in der Gameconfig implementiert?

**Comment by nicories** [comment]
@BroderPeters Ich hab da ehrlich gesagt noch gar nicht dran gearbeitet.
Sollen die PlayerConfigs wirklich weg und die Attribute für die Ameisen werden beim Kaufen festgelegt?

**Comment by jmattheis** [comment]
Yep, so ist es geplant.

**Comment by BroderPeters** [comment]
Stimme zu.
