### ISSUE TITLE
Properties der Ants

### ISSUE THREAD

**Issue by BroderPeters** [jmattheis/AntWars#79]
Durch die aktuell zahlreichen Veränderungen im Projekt würde ich gern einmal, unter anderem für den Kostenrechner der Ameisen (#74), die aktuellen Properties der Ameise auflisten:
Implementiert: ViewRange, MoveRange, Inventory, Cost

Soll gelöscht werden: Speed

Soll implementiert werden: Health, Power

Stimmt das so?

**Comment by BroderPeters** [comment]
@nicolasries @jmattheis @arndtphillip Bitte um Feedback um #74 fertigzustellen.

**Comment by nicories** [comment]
Ich würde nur davon ausgehen, was aktuell im master ist, also ViewRange, Inventory und Cost.

**Comment by jmattheis** [comment]
Eigentlich sollte @arndtphillip das mit dem Speed ja implementieren, wenn ich jetzt so aber mal darüber nachdenke ich es eigentlich ziemlich doof wenn eine Ameise pro tick 2 Felder gehen kann

**Comment by nicories** [comment]
Das kann zu oder?

**Comment by BroderPeters** [comment]
Habe es für die Einführung der Warrior-Klasse offen gelassen.

> Soll implementiert werden: Health, Power

**Comment by nicories** [comment]
das steht im Kampf Issue drin
