### ISSUE TITLE
Zucker ablegen range

### ISSUE THREAD

**Issue by jmattheis** [jmattheis/AntWars#82]
Man sollte zucker auf der Base auch ablegen können wenn man im umkreis von 2 Feldern bei der Base steht.

**Comment by BroderPeters** [comment]
Ist das echt notwendig? wenn es Probleme beim Zucker ablegen gibt dann muss die KI entsprechend programmiert werden.

**Comment by jmattheis** [comment]
Notwendig ist dies wenn man viele Ameisen hat, wenn die dann alle auf einen Punkt laufen müssen und dann Klumpen, kann man eigentlich schon nix mehr machen UND es wäre auch lögisch das die base "größer" wird bei mehr Ameisen, vielleicht sollte man das dann je nach Ameisen Anzahl verändern.

**Comment by BroderPeters** [comment]
Die Lösung gefällt mir schon besser.
Ich würde vorschlagen nach x Zucker wird die Base um x vergrößert.
