### ISSUE TITLE
Projekt-Präsentation

### ISSUE THREAD

**Issue by nicories** [jmattheis/AntWars#85]
So langsam sollten wir uns Gedanken darüber machen, wie wir das Projekt in der Schule vorstellen möchten. Dieses Issue dient zum Ideen sammeln und besprechen.
Meine ersten Ideen:
- UML-Diagramm, um an den Unterrichtsstoff anzuschließen
- Code des Programms teilweise durchgehen, interessante Stellen vorstellen
- Natürlich das Programm einmal in Action zeigen, indem wir zwei AIs gegeneinandern antreten lassen
- Vllt ein bisschen über git reden, wie das war damit im Team zu arbeiten etc

**Comment by BroderPeters** [comment]
Nebenbei oder als Leitfaden die Projektdokumentation (welche ich noch ergänzen müsste).
Wichtig ist auch wer was macht. Ich habe keine Lust mehr auf ungleiche Arbeitsverteilung. Vor allem nicht bei einer Aufgabe wo jeder einen guten Teil beitragen kann.

**Comment by BroderPeters** [comment]
@jmattheis hast du hierzu noch Vorschläge?

**Comment by jmattheis** [comment]
Das von @nicolasries deckt glaube ich schon fast alles ab, das einzige was mir noch einfallen würde, wäre Performance wieso wir da und da zb ein array genutzt haben statt ein Directory, aber ich denke das fällt auch unter `Code des Programms teilweise durchgehen, interessante Stellen vorstellen`

**Comment by BroderPeters** [comment]
@nicolasries @jmattheis @arndtphillip Ich schlage vor dass wir morgen ein Teamspeak-Meeting abhalten und ein bisschen den aktuellen Stand sowie die anstehende Präsentation besprechen. Das Meeting sollte entweder frühs oder abends sein. (so hat jeder noch etwas vom tag) Meinungen?

**Comment by jmattheis** [comment]
ist k für mich

**Comment by BroderPeters** [comment]
Egal wann?

**Comment by nicories** [comment]
Ja bin ich auch dabei. Ich fänd abends besser.

**Comment by BroderPeters** [comment]
20 uhr?

**Comment by nicories** [comment]
Ist in Ordnung.

**Comment by BroderPeters** [comment]
@jmattheis kannst du nochmal die Serverinformationen deines TS3-Servers schicken bzw. hier schreiben?

**Comment by jmattheis** [comment]
`ts.justaserver.de`

**Comment by BroderPeters** [comment]
Ablauf:
1. Einleitung (Broder)
2. UML-Diagramm (?)
3. Besonderer Code:
    - Kreisberechnung
    - dll-Loader
4. Performancebegründung (Jannis)
5. Präsentation AntWars (Alle) - KI von Entwicklern nutzen
6. Auswertung der Teamarbeit (Anhand Projektdokumentation)
7. Beantwortung von Fragen (Alle)

**Comment by nicories** [comment]
Seid ihr schon fertig? Sorry wollte eigentlich auch kommen aber mein Internet spinnt gerade...

**Comment by BroderPeters** [comment]
Ja, sind wir.
Haben es erstmal bei dem Ablauf belassen.
Müssen uns dann morgen in der Schule kurzschließen.

**Comment by jmattheis** [comment]
Man könnte auch soetwas machen wie sich der Code so über die Zeit verändert hat,
zb:
- Performance `#getBoardObectsInView`
- UI Design
- KI

Damit könnten wir dann Code-Design Entscheidungen erklären, ich denke das wäre interessant.

**Comment by BroderPeters** [comment]
@jmattheis @nicolasries Ich denke auch dass sich das positiv auf die Präsentation auswirkt, vor allem da ihr beide so euren Anteil viel besser darstellen könnt.
Schlage vor, dass wir das am Wochenende anstatt des geplanten "Grafik-Meetings" mal besprechen.

**Comment by nicories** [comment]
Ja das ist eine gute Idee. Sonntag Abend?

**Comment by jmattheis** [comment]
Ich hab am Wochenende noch nichts vor kann also eigentlich immer (:

**Comment by BroderPeters** [comment]
Wenn @nicolasries nur Sonntag passt, dann Sonntag.
Ansonsten hätte ich an Samstag gedacht.

**Comment by nicories** [comment]
Wäre mir lieber wenn es euch nichts ausmacht

**Comment by BroderPeters** [comment]
Für mich wäre es passend.

**Comment by jmattheis** [comment]
Wieviel Uhr?

**Comment by nicories** [comment]
20:00?

**Comment by BroderPeters** [comment]
jo

**Comment by BroderPeters** [comment]
@nicolasries Konntest du bereits etwas für die Darstellung per UML tun?

**Comment by nicories** [comment]
Hab ehrlich gesagt noch gar nicht angefangen. Ich wollte das erst machen, wenn wir fertig sind, damit das Diagramm auf dem aktuellen Stand ist.

**Comment by nicories** [comment]
Also das UML-Diagramm ist fertig und gepusht.
Wir brauchen für die Präsentation, wenn wir die morgen halten, noch wenigstens eine funktionierende AI und das fertig erstellte Programm. Außerdem sollten wir aufteilen, wer was vorstellt.

**Comment by BroderPeters** [comment]
Ich wäre dafür das wir morgen auf ihn zugehen und mit ihm planen, wie wir die Präsentation in den Unterricht eingliedern können, da er ja letzte Woche krank war.

**Comment by nicories** [comment]
Ok, können wir so machen.
