### ISSUE TITLE
Aufgabenübertragung

### ISSUE THREAD

**Issue by BroderPeters** [jmattheis/AntWars#87]
Wir befinden uns aktuell in der letzten Woche vor der Vorstellung unseres Projektes. Meiner Meinung nach ist die Aufgabenverteilung aber ungleichmäßg. Was haltet ihr (besonders @jmattheis und @nicolasries ) davon wenn wir die Aufgaben gleichmäßig verteilen? Natürlich je nach Kenntnissen der Personen.

**Comment by nicories** [comment]
Ich habe eigentlich kein Problem mit der Verteilung gerade. Ich habe im Moment auch Zeit und Lust auf das Projekt, deswegen kann ich auch etwas mehr daran arbeiten.
Wenn ihr etwas machen wollt, was gerade mir zugeordnet ist, kann man das aber natürlich klären.

**Comment by jmattheis** [comment]
Denke hier ist nix mehr zu machen.
