### ISSUE TITLE
Ameisen Attribute in der AI festlegen

### ISSUE THREAD

**Issue by nicories** [jmattheis/AntWars#89]
Die Attribute der Ameisen (Sichtweite, Inventargröße, etc) sollen nun dynamisch während des Kaufens in der AI festgelegt werden können.
Die AI der Spieler kommt in die GameConfig, damit wird die PlayerConfig obsolet und kann gelöscht werden.
Hinterher muss dann nochmal die Tab Reihenfolge gefixt werden...

**Comment by BroderPeters** [comment]
Yeah, Tab Reihenfolge
