### ISSUE TITLE
Bewegungserweiterung

### ISSUE THREAD

**Issue by BroderPeters** [jmattheis/AntWars#96]
Vorschlag: Ameisen sollen sich auch Diagonal bewegen können.

**Comment by jmattheis** [comment]
Das kannst du bereits indem du dich einmal nach unten/oben und dann zur seite bewegst.

**Comment by BroderPeters** [comment]
Ja, jedoch nimmt dies zwei ticks in Anspruch, benutzt jedoch nur eine Bewegung.

**Comment by BroderPeters** [comment]
@jmattheis @nicolasries Was haltet ihr von der Möglichkeit dass sich eine Ameise in der Base wieder erholen kann, also die UnitsGone zurücksetzt? Würde der KI noch ein weiteres Feature zur Verfügung stellen.

**Comment by jmattheis** [comment]
sollten sie doch. hat  @arndtphillip vergessen, dabei hatte ich das sogar noch in den pr geschrieben .___.

**Comment by BroderPeters** [comment]
Gibt es dazu ein Issue?
Edit:

> Insgesamten Bewegungen der Ameise soll auf 0 gesetzt werden, wenn die Ameise auf der Base steht / in der Range von der Base ist, dass man Zucker ablegen kann, dazu kannst du dir den Commit 931d45c ansehen

Ja hattest du erwähnt. Ich würde `UnitsGone = 0;` in `dropSugarOnBase()`Methode hinzufügen.

**Comment by BroderPeters** [comment]
@jmattheis @nicolasries Können die Methoden für Diagonales bewegen hinzugefügt werden, oder gibt es hierzu noch Gegenargumente?

**Comment by nicories** [comment]
Kann gemacht werden.

**Comment by jmattheis** [comment]
@BroderPeters siehste das solves closed das Issue nicht automatisch.
siehe https://help.github.com/articles/closing-issues-via-commit-messages/ für alle Wörter die das machen.
